import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";

import NavBar from "../components/NavBar/NavBar";
import Header from "../components/Header/Header";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />
      <Header />

      <main className={styles.main}></main>

      <footer className={styles.footer}>
   
      </footer>
    </div>
  );
};

export default Home;
